version: '3'
services:
  web:
    image: my-app-web
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped

  api:
    image: my-app-api
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped