version: '3.8'

services:
  web:
    image: web-app
    container_name: web-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - app-network

  docs:
    image: docs-app
    container_name: docs-app
    restart: unless-stopped
    ports:
      - "4000:3000"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge