version: '3.8'

services:
  web:
    image: turbo-apps
    command: ["web"]
    ports:
      - "3000:3000"
    restart: unless-stopped

  docs:
    image: turbo-apps
    command: ["docs"]
    ports:
      - "4000:3000"
    restart: unless-stopped