name: Turbo Docker Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Единая сборка всех приложений
      - name: Build with Turbo
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            args: []
          run_build: |
            args: []

      # 2. Создаем универсальный Docker-образ
      - name: Build Docker Image
        run: |
          docker build \
            --build-arg APP_NAME=web \
            -t web-app \
            -f ./.docker/Dockerfile .

          docker build \
            --build-arg APP_NAME=docs \
            -t docs-app \
            -f ./.docker/Dockerfile .

          docker save web-app docs-app | gzip > apps.tar.gz

      # 3. Деплой на сервер
      - name: Deploy to Server
        run: |
          scp -i ~/.ssh/key apps.tar.gz docker-compose.prod.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/app/
          ssh -i ~/.ssh/key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            cd /app
            docker load -i apps.tar.gz
            docker compose -f docker-compose.prod.yml up -d --force-recreate
          "