name: Deploy Next.js Apps

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Установка pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      # 2. Установка зависимостей с кэшированием
      - name: Install dependencies
        uses: pnpm/action-setup@v2
        with:
          run_install: true
          args: --frozen-lockfile

      # 3. Сборка проектов через Turborepo
      - name: Build with Turbo
        run: pnpm turbo run build --filter=web --filter=docs

      # 4. Сборка Docker-образов
      - name: Build Docker images
        run: |
          docker build -t web-app -f apps/web/Dockerfile .
          docker build -t docs-app -f apps/docs/Dockerfile .
          docker save web-app docs-app | gzip > apps.tar.gz

      # 5. Настройка SSH
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/key
          chmod 600 ~/.ssh/key
          ssh-keyscan ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      # 6. Деплой
      - name: Deploy to Server
        run: |
          scp -i ~/.ssh/key apps.tar.gz docker-compose.prod.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/app/
          ssh -i ~/.ssh/key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            cd /app
            docker load -i apps.tar.gz
            docker compose -f docker-compose.prod.yml up -d --force-recreate
          "