name: Turbo Docker Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Установка зависимостей
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 2. Сборка всех приложений
      - name: Build with Turbo
        run: pnpm turbo run build

      # 3. Отдельная сборка Docker-образов
      - name: Build Docker Images
        run: |
          docker build -t web-app -f apps/web/Dockerfile .
          docker build -t docs-app -f apps/docs/Dockerfile .
          docker save web-app docs-app | gzip > apps.tar.gz

      # 4. Деплой
      - name: Deploy to Server
        run: |
          scp -i ~/.ssh/key apps.tar.gz docker-compose.prod.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/app/
          ssh -i ~/.ssh/key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            cd /app
            docker load -i apps.tar.gz
            docker compose -f docker-compose.prod.yml up -d --force-recreate
          "