name: Deploy via Image Transfer

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t my-app -f apps/web/Dockerfile .
          docker save my-app | gzip > my-app.tar.gz

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/key
          chmod 600 ~/.ssh/key
          ssh-keyscan ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Transfer and Deploy
        run: |
          scp -i ~/.ssh/key my-app.tar.gz ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/tmp/
          ssh -i ~/.ssh/key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          docker load -i /tmp/my-app.tar.gz
          docker stop my-app || true
          docker rm my-app || true
          docker run -d \
            -p 3000:3000 \
            --name my-app \
            --restart unless-stopped \
            my-app
          rm /tmp/my-app.tar.gz
          EOF