name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/key
          chmod 600 ~/.ssh/key
          ssh-keyscan ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Upload compose file
        run: |
          scp -i ~/.ssh/key docker-compose.prod.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/app/

      - name: Prepare Server Directory
        run: |
          ssh -i ~/.ssh/key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          mkdir -p /app
          cd /app
          if [ -d .git ]; then
            git pull origin main
          else
            git clone https://github.com/${{ github.repository }}.git /app
          fi
          EOF

      - name: Deploy Application
        run: |
          ssh -i ~/.ssh/key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd /app
          git checkout main
          git reset --hard origin/main
          docker compose down
          docker compose build --no-cache
          docker compose up -d
          EOF