name: Deploy Next.js Apps

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Установка зависимостей с Turbo-кэшированием
      - name: Install dependencies
        run: |
          pnpm install
          pnpm turbo run build --filter=web --filter=docs

      # 2. Сборка Docker-образов (мультистадийная)
      - name: Build Docker images
        run: |
          docker build -t web-app -f apps/web/Dockerfile .
          docker build -t docs-app -f apps/docs/Dockerfile .
          docker save web-app docs-app | gzip > apps.tar.gz

      # 3. Деплой на сервер
      - name: Deploy to Server
        run: |
          scp -i ~/.ssh/key apps.tar.gz docker-compose.prod.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/app/
          ssh -i ~/.ssh/key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            cd /app && \
            docker load -i apps.tar.gz && \
            docker compose -f docker-compose.prod.yml up -d --force-recreate
          "